[[language]]
name = "markdoc"
scope = "text.markdoc"
roots = []
file-types = ["mdoc"]

[[grammar]]
name = "markdoc"
source = { git = "https://github.com/markdoc-extra/tree-sitter-markdoc", rev = "89c62c8f3b407fbd46f08b569342a3469c5b374b" }