- name: Set up local development environment
  hosts: localhost
  connection: local

  pre_tasks:
  - name: Setup system variables
    tags:
      - always
    include_vars:
      file: vars/system.yml
  - name: Setup config variables
    tags:
      - always
    include_vars:
      file: vars/config.yml

  roles:
    # Software
    - {role: fd, tags: ['fd']}
    - {role: bat, tags: ['bat']} 
    - {role: fzf, tags: ['fzf']}
    - {role: exa, tags: ['exa']}
    - {role: nap, tags: ['nap']} # @TODO - File config (pending next release)
    - {role: zsh, tags: ['zsh']}
    - {role: xplr, tags: ['xplr']}
    - {role: asdf, tags: ['asdf', 'deno', 'node', 'ruby']}
    - {role: focus, tags: ['focus']}
    - {role: gitui, tags: ['gitui']}
    - {role: helix, tags: ['helix']}
    - {role: rsync, tags: ['rsync']}
    - {role: slides, tags: ['slides']}
    - {role: zoxide, tags: ['zoxide']}
    - {role: silicon, tags: ['silicon']}
    - {role: sheldon, tags: ['sheldon']}
    - {role: tealdeer, tags: ['tealdeer']} 
    - {role: starship, tags: ['starship']} 
  
    # Configs
    - {role: config-zsh, tags: ['config', 'config-zsh']}
    - {role: config-bat, tags: ['config', 'config-bat']}
    - {role: config-nap, tags: ['config', 'config-nap']}
    - {role: config-helix, tags: ['config', 'config-helix']}
    - {role: config-wezterm, tags: ['config', 'config-wezterm']}
    - {role: config-sheldon, tags: ['config', 'config-sheldon']}
    - {role: config-starship, tags: ['config', 'config-starship']}
  
    # Languages
    - {role: go, tags: ['go', 'lsp_go']}
    # Deno packages it's own LSP as part of it's binary
    - {role: deno, tags: ['deno']}
    - {role: node, tags: ['node', 'lsp_node']}
    - {role: ruby, tags: ['ruby', 'ruby_lsp']}
    - {role: rust, tags: ['rust', 'lsp_rust']}
  
    # LSP (for Helix)
    # These could technically be part of the language installs
    # But there may be instances where we want the language only
    - {role: lsp_go, tags: ['lsp_go']}
    - {role: lsp_rust, tags: ['lsp_rust']}
    - {role: lsp_node, tags: ['lsp_node']}
    - {role: lsp_ruby, tags: ['lsp_ruby']}
  
