# See comments on package page
# - https://build.opensuse.org/package/show/openSUSE:Factory/helix
- name: Install Helix on openSUSE
  become: yes
  zypper:
    name: 
      - helix
      - helix-runtime
    state: present

- name: Create local bin if it doesn't exist
  file:
    mode: 0755
    path: "{{ local_bin }}"
    state: directory
    recurse: yes

- name: Create symbolic link to `hx` command
  ansible.builtin.file:
    src: "{{ vendor_bin }}/helix"
    dest: "{{ local_bin }}/hx"
    state: link

