# We use version 17 because it is the latest officially supported version
# - https://clojure.org/guides/install_clojure#java
- name: Install open JDK on openSUSE
  become: yes
  zypper:
    name: 
      - java-17-openjdk-devel
      - leiningen
    state: present
