- name: Install required packages on openSUSE
  become: yes
  community.general.zypper:
    name:
      - libharfbuzz0
      - libfontconfig1
      - libxcb1
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - python310-github3.py
    state: present

- name: Get latest Silicon release from GitHub on openSUSE
  community.general.github_release:
    user: Aloxaf
    repo: silicon
    action: latest_release
  register: silicon_release

- name: Create local bin if it doesn't exist
  file:
    mode: 0755
    path: "{{ local_bin }}"
    state: directory
    recurse: yes

- name: Unzip and install Silicon on openSUSE
  unarchive:
    src: "https://github.com/Aloxaf/silicon/releases/download/{{ silicon_release['tag'] }}/silicon-{{ silicon_release['tag'] }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ local_bin }}"
    remote_src: true
    creates: "{{ local_bin }}/silicon"
