shell = "zsh"

[templates]
# https://github.com/rossmacarthur/sheldon/issues/154
completion = "ln -sf {{ files.0 }} ~/.zsh_completions/_{{ name }}"  # only uses first matched file

[plugins.fzf]
github = "junegunn/fzf"
dir = "shell"
use = ["key-bindings.zsh"]
