promptToReturnFromSubprocess: false

os:
  editPreset: 'helix'

git:
  log:
    showGraph: never
  paging:
    # Use difftastic for syntax aware diffs
    externalDiffCommand: difft --color=always --display=inline --tab-width=2  --syntax-highlight=off

gui:
  border: single
  # Requires restart to see
  authorColors:
    '*': 'default'
  sidePanelWidth: 0.2
  refreshInterval: 1
