- name: Install github3 on openSUSE
  become: yes
  community.general.zypper:
    # Required by the community `github_release` module
    name: python310-github3.py
    state: present

- name: Get latest focus release from GitHub on openSUSE
  community.general.github_release:
    token: "{{ github_token | default('') }}"
    user: ayoisaiah
    repo: focus
    action: latest_release
  register: focus_release

- name: Install focus using remote rpm on openSUSE
  become: yes
  community.general.zypper:
    name: "https://github.com/ayoisaiah/focus/releases/download/{{ focus_release['tag'] }}/focus_{{ focus_release['tag'] | regex_replace('^v','') }}_linux_amd64.rpm"
    state: present
    # Unfortunately we need to include this to prevent an interactive popup mid install (which crashes Ansible)
    disable_gpg_check: yes

