[templates]
completion = "ln -sf {{ files.0 }} ~/.zsh_completions/_{{ name }}"  # only uses first matched file

[plugins.fd]
github = "sharkdp/fd"
dir = "contrib/completion"
apply = ["fpath"]

[plugins.exa]
github = "ogham/exa"
dir = "completions/zsh"
apply = ["fpath"]

[plugins.asdf]
github = "asdf-vm/asdf"
dir = "completions"
apply = ["fpath"]

# https://github.com/rossmacarthur/sheldon/issues/154
[plugins.sheldon]
remote = "https://raw.githubusercontent.com/rossmacarthur/sheldon/trunk/completions/sheldon.zsh"
apply = ["completion"]

# https://github.com/rossmacarthur/sheldon/issues/154
[plugins.vcsh]
remote = "https://raw.githubusercontent.com/RichiH/vcsh/main/completions/vcsh.zsh"
apply = ["completion"]

[plugins.fzf]
github = "junegunn/fzf"
dir = "shell"
use = ["completion.zsh", "key-bindings.zsh"]

[plugins.base16-fzf]
github = "base16-project/base16-fzf"
use = ["bash/base16-gruvbox-dark-medium.config"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

