- name: Install github3 python package on macOS
  ansible.builtin.pip:
    name: github3.py

- name: Install gnu-tar on macOS
  homebrew: 
    name: gnu-tar
    state: present

- name: Get latest nap release from GitHub on macOS
  community.general.github_release:
    token: "{{ github_token | default('') }}"
    user: maaslalani
    repo: nap
    action: latest_release
  register: nap_release

- name: Create local bin if it doesn't exist
  file:
    mode: 0755
    path: "{{ local_bin }}"
    state: directory
    recurse: yes

- name: Unzip and install nap on macOS
  unarchive:
    src: "https://github.com/maaslalani/nap/releases/download/{{ nap_release['tag'] }}/nap_{{ nap_release['tag'] | regex_replace('^v','') }}_darwin_amd64.tar.gz"
    dest: "{{ local_bin }}"
    remote_src: true
    creates: "{{ local_bin }}/nap"
    include:
     - nap
