- name: Install github3 on openSUSE
  become: yes
  community.general.zypper:
    # Required by the community `github_release` module
    name: python310-github3.py
    state: present
- name: Get latest nap release from GitHub on openSUSE

  community.general.github_release:
    token: "{{ github_token | default('') }}"
    user: maaslalani
    repo: slides
    action: latest_release
  register: slides_release

- name: Create local bin if it doesn't exist
  file:
    mode: 0755
    path: "{{ local_bin }}"
    state: directory
    recurse: yes

- name: Unzip and install Slides on openSUSE
  unarchive:
    src: "https://github.com/maaslalani/slides/releases/download/{{ slides_release['tag'] }}/slides_{{ slides_release['tag'] | regex_replace('^v','') }}_linux_amd64.tar.gz"
    dest: "{{ local_bin }}"
    remote_src: true
    creates: "{{ local_bin }}/slides"
    include:
     - slides
