- name: Synchronize Zsh config
  file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    state: link
  with_items:
    - { src: '.zshrc', dest: '.zshrc' }
    - { src: '.zshenv', dest: '.zshenv' }
    - { src: '.zsh_functions', dest: '.zsh_functions' }
    - { src: '.zsh_wsl_helpers', dest: '.zsh_wsl_helpers' }
