- name: Install github3 on openSUSE
  become: yes
  community.general.zypper:
    # Required by the community `github_release` module
    name: python310-github3.py
    state: present

- name: Get latest gitui release from GitHub on openSUSE
  community.general.github_release:
    token: "{{ github_token | default('') }}"
    user: extrawurst
    repo: gitui
    action: latest_release
  register: gitui_release

- name: Create local bin if it doesn't exist
  file:
    mode: 0755
    path: "{{ local_bin }}"
    state: directory
    recurse: yes

- name: Unzip and install gitui on openSUSE
  unarchive:
    src: "https://github.com/extrawurst/gitui/releases/download/{{ gitui_release['tag'] }}/gitui-linux-musl.tar.gz"
    dest: "{{ local_bin }}"
    remote_src: true
    creates: "{{ local_bin }}/gitui"
