- name: Install github3 python package on macOS
  pip:
    name: github3.py

- name: Get latest the-way release from GitHub on macOS
  community.general.github_release:
    token: "{{ github_token | default('') }}"
    user: out-of-cheese-error
    repo: the-way
    action: latest_release
  register: the_way_release

- name: Create local bin if it doesn't exist
  file:
    mode: 0755
    path: "{{ local_bin }}"
    state: directory
    recurse: yes

- name: Unzip and install the-way on macOS
  unarchive:
    src: "https://github.com/out-of-cheese-error/the-way/releases/download/{{ the_way_release['tag'] }}/the-way-macos.tar.gz"
    dest: "{{ local_bin }}"
    remote_src: true
    creates: "{{ local_bin }}/the-way"
