- name: Add Docker repository
  zypper_repository:
    name: Docker
    repo: 'https://download.docker.com/linux/opensuse/distribution/leap/$releasever/stable'
    state: present

- name: Refresh repositories
  command: zypper refresh

- name: Install Docker Community Edition
  zypper:
    name: docker-ce
    state: present

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add current user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes

- name: Start Docker service
  systemd:
    name: docker
    state: started
