- name: Create Neovim config direcotry
  file:
    path: "{{ config_dir }}/nvim"
    state: directory
    recurse: yes
    mode: "0755"

- name: Synchronize Neovim config
  file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ config_dir }}/nvim/{{ item.dest }}"
    state: link
  with_items:
    - { src: 'fnl', dest: 'fnl' }
    - { src: 'init.lua', dest: 'init.lua' }
